version: "3"

services: 
  vrising:
    build:
        context: .
        args:
          STEAM_EPOCH:
          UID: ${UID}
          GID: ${GID}
    volumes: 
      - $HOME/vrising-server:/vrising/server-data
    ports: 
      - "27015-27016:27015-27016/udp"
    restart: unless-stopped
    stop_grace_period: 2m

